# Generated by Django 5.2.1 on 2025-05-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
