# Generated by Django 5.2.1 on 2025-05-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(default="test@email.com", max_length=254),
            preserve_default=False,
        ),
    ]
